services:
  database:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=ironslayer'
      - 'POSTGRES_DB=ecommerce_db'
      - 'POSTGRES_PASSWORD=ironslayer'
    volumes:
      - './volumes/ecommerce-db/postgres:/var/lib/postgresql/data'
